package edu.qut.data.questions.model.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

/** DynamoDB based POJO */
@DynamoDBTable(tableName = "QuestionPoll")
public class QuestionPoll {

    private String id;
    private String question;
    private String publishedAt;
    private List<QuestionChoice> choices;

    public QuestionPoll() {
    }

    public QuestionPoll(String question, String publishedAt, List<QuestionChoice> choices) {
        this.question = question;
        this.publishedAt = publishedAt;
        this.choices = choices;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "Question")
    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    @DynamoDBAttribute(attributeName = "PublishedAt")
    public String getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    @DynamoDBAttribute(attributeName = "Choices")
    public List<QuestionChoice> getChoices() {
        return choices;
    }

    public void setChoices(List<QuestionChoice> choices) {
        this.choices = choices;
    }
}